name: mt_llmkit
version: 0.0.1-beta.1
description: A Flutter plugin for running Large Language Models locally on Android and iOS via llama.cpp, with real-time streaming inference and performance metrics.
homepage: https://github.com/mobitouchOS/mt_llmkit
repository: https://github.com/mobitouchOS/mt_llmkit
issue_tracker: https://github.com/mobitouchOS/mt_llmkit/issues
topics:
  - llm
  - llama-cpp
  - ai
  - on-device-ai
  - flutter-plugin

environment:
  sdk: '>=3.10.7 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  llamadart: ^0.6.10
  http: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: net.mobitouch.llmkit
        pluginClass: LlmcppPlugin
      ios:
        pluginClass: LlmcppPlugin
      # web:
      #   pluginClass: LlmcppWeb
      #   fileName: llmcpp_web.dart
