// lib/src/rag/document/document_chunk.dart

/// A document fragment (chunk) with an optional embedding vector.
///
/// Chunks are created by [TextChunker] from [Document.content].
/// The [embedding] field is `null` until it is filled in
/// by [EmbeddingProvider.embed(chunk.text)].
///
/// JSON serialization supports `List<double>?` embedding.
class DocumentChunk {
  /// Unique chunk identifier: "${documentId}_chunk_${chunkIndex}"
  final String id;

  /// Source document identifier
  final String documentId;

  /// Text of this fragment
  final String text;

  /// Chunk index within the document (0-based)
  final int chunkIndex;

  /// Start position in the original document text (inclusive)
  final int startChar;

  /// End position in the original document text (exclusive)
  final int endChar;

  /// Embedding vector — `null` until [EmbeddingProvider.embed] is called.
  ///
  /// Mutable: set after the embedding is generated by [RagPipeline].
  List<double>? embedding;

  /// Chunk metadata (inherited from the document or additional)
  final Map<String, dynamic> metadata;

  DocumentChunk({
    required this.id,
    required this.documentId,
    required this.text,
    required this.chunkIndex,
    required this.startChar,
    required this.endChar,
    this.embedding,
    Map<String, dynamic>? metadata,
  }) : metadata = metadata ?? {};

  // ── Getters ───────────────────────────────────────────────────────────────

  /// Whether this chunk has a generated embedding
  bool get hasEmbedding => embedding != null;

  /// Number of characters in the chunk text
  int get length => text.length;

  /// Text preview (first 80 characters)
  String get preview {
    if (text.length <= 80) return text;
    return '${text.substring(0, 77)}...';
  }

  // ── Serialization ────────────────────────────────────────────────────────

  Map<String, dynamic> toJson() => {
        'id': id,
        'documentId': documentId,
        'text': text,
        'chunkIndex': chunkIndex,
        'startChar': startChar,
        'endChar': endChar,
        // List<double> → List<dynamic> (JSON compatible)
        'embedding': embedding,
        'metadata': metadata,
      };

  factory DocumentChunk.fromJson(Map<String, dynamic> json) {
    final rawEmbedding = json['embedding'] as List<dynamic>?;
    return DocumentChunk(
      id: json['id'] as String,
      documentId: json['documentId'] as String,
      text: json['text'] as String,
      chunkIndex: json['chunkIndex'] as int,
      startChar: json['startChar'] as int,
      endChar: json['endChar'] as int,
      embedding: rawEmbedding?.map((e) => (e as num).toDouble()).toList(),
      metadata: (json['metadata'] as Map<String, dynamic>?) ?? {},
    );
  }

  @override
  String toString() =>
      'DocumentChunk(id: $id, chars: $length, hasEmbedding: $hasEmbedding)';
}
